name: 'GitHub Action - Azure Web App Route Traffic to Slot'
description: 'Route a percentage of traffic to an Azure Web App Slot'
author: 'Colin Dembovsky'
inputs:
  resource-group:
    description: 'Name of the resource group containing the web app'
    required: true
  app-name:
    description: 'Name of the web app'
    required: true
  slot-name:
    description: 'Name of the slot to route percentage of traffic to'
    required: true
  percentage-traffic:
    description: 'Percentage of traffic to route to slot'
    required: true
branding:
  icon: 'cloud'
  color: 'blue'
runs:
  using: 'node12'
  main: 'dist/index.js'
