name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: az account get-access-token

    - name: 'Test traffic routing'
      uses: ./
      with: 
        resource-group: cd-pu2-prod-webapp
        app-name: cdpartsun2-prod
        slot-name: blue
        percentage-traffic: 21
    
    - name: Azure logout
      run: |
        az logout